app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include (('bases.urls','bases'), namespace='bases')),
    path('inv/', include (('inv.urls','inv'), namespace='inv')),
    path('cmp/', include (('cmp.urls','cmp'), namespace='cmp')),
    path('admin/', admin.site.urls),
]

cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, proveedorInactivar,\
    ComprasView, compras

urlpatterns = [

    path('proveedor/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedor/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedor/inactivar/<int:id>', proveedorInactivar, name='proveedor_inactivar'),

    path('compras/', ComprasView.as_view(), name='compras_list'),
    path('compras/new',compras, name="compras_new"),
]

cmp/models.py
from django.db import models
from bases.models import ClaseModelo
from inv.models import Producto

# Create your models here.
class Proveedor (ClaseModelo):
    descripcion=models.CharField(max_length=100, unique=True)
    direccion=models.CharField(max_length=250, null=True, blank= True)
    contacto=models.CharField(max_length=100)
    telefono=models.CharField(max_length=10, null=True, blank=True)
    email=models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural= "Proveedores"



class ComprasEnc(ClaseModelo):
    fecha_compra=models.DateField(null=True, blank=True)
    observacion=models.TextField(null=True, blank=True)
    no_factura=models.CharField(max_length=100)
    fecha_factura=models.DateField()
    sub_total=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    descuento=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    total=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    
    proveedor=models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.observacion)

    def save (self):
        self.observacion = self.observacion.upper()
        self.total =self.sub_total - self.descuento
        super(ComprasEnc, self).save()

    class Meta:
        verbose_name_plural="Encabezado Compras"
        verbose_name="Encabezado Compra"


class Comprasdet(ClaseModelo):
    compra=models.ForeignKey(ComprasEnc, on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    sub_total=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    descuento=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    total=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    costo=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    
    def __str__(self):
        return '{}'.format(self.producto)

    def save (self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total=self.sub_total - float(self.descuento)
        super(Comprasdet, self).save()

    class Meta:
        verbose_name_plural="Detalles Compras"
        verbose_name="Detalle Compra"

cmp/forms.py
from django import forms
from .models import Proveedor, ComprasEnc


class ProveedorForm(forms.ModelForm):
    class Meta:
        model=Proveedor
        exclude=['um', 'fm', 'uc', 'fc']        
        widget= {'descripcion': forms.TextInput()}

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class ComprasEncForm(forms.ModelForm):
    fecha_compra = forms.DateInput()
    fecha_factura = forms.DateInput()
    
    class Meta:
        model=ComprasEnc
        fields=['proveedor','fecha_compra','observacion',
            'no_factura','fecha_factura','sub_total',
            'descuento','total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

cmp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.views import generic
from django.urls import reverse_lazy
import datetime

from django.http import HttpResponse
import json
from .models import Proveedor, ComprasEnc, Comprasdet
from cmp.forms import ProveedorForm, ComprasEncForm
from bases.views import SinPrivilegios
from inv.models import Producto


# Create your views here.
class ProveedorView(SinPrivilegios, generic.ListView):
     model = Proveedor
     template_name = "inv/proveedor_list.html"
     context_object_name = "obj"
     permission_required = "cmp.view_proveedor"

class ProveedorNew (SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required="cmp.add_proveedor"
    model=Proveedor
    template_name="cmp/proveedor_form.html"
    context_object_name="obj"
    form_class=ProveedorForm
    success_url=reverse_lazy("cmp:proveedor_list")
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class ProveedorEdit (SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
     permission_required="cmp.change_proveedor"
     model=Proveedor
     template_name="cmp/proveedor_form.html"
     context_object_name="obj"
     form_class=ProveedorForm
     success_url=reverse_lazy("cmp:proveedor_list")
     
     def form_valid(self, form):
         form.instance.um = self.request.user.id
         return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('cmp:change_proveedor', login_url='/login/')
def proveedorInactivar(request,id):
    template_name='cmp/inactivar_prv.html'
    contexto={}
    prv = Proveedor.objects.filter(pk=id).first()

    if not prv:
        return HttpResponse('Proveedor no existe' + str(id))

    if request.method== 'GET':
        contexto={'obj':prv}

    if request.method=='POST':
        prv.estado=False
        prv.save()
        contexto={'obj':'OK'}
        return HttpResponse('Proveedor Inactivado')

    return render(request, template_name, contexto)



class ComprasView(SinPrivilegios, generic.ListView):
    model = ComprasEnc
    template_name = "cmp/compras_list.html"
    context_object_name = "obj"
    permission_required = "cmp.view_comprasenc"


@login_required(login_url='/login/')
@permission_required('cmp:view_compras', login_url='bases:sin_privilegios')
def compras(request,compra_id=None):
    template_name = "cmp/compras.html"
    prod = Producto.objects.filter(estado=True)
    form_compras = {}
    contexto = {}

    if request.method=='GET':
        form_compras=ComprasEncForm()
        enc=ComprasEnc.objects.filter(pk=compra_id).first()

        if enc:
            det = Comprasdet.objects.filter(compras=enc)
            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            fecha_factura = datetime.date.isoformat(enc.fecha_factura)
            e = {
                'fecha_compra':fecha_compra,
                'proveedor':enc.proveedor,
                'observacion': enc.observacion,
                'no_factura': enc.no_factura,
                'fecha_factura':enc.fecha_factura,
                'subtotal':enc.subtotal,
                'descuento':enc.descuento,
                'total':enc.total
            }

            form_compras = ComprasEncForm(e)
        else:
            det=None

        contexto={'producto':prod, 'encabezado':enc, 'detalle':det, 'form_enc':form_compras}

        return render(request, template_name, contexto)

cmp/templates/cmp/compras_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Compras</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>          
          <a class="dropdown-item" href="{% url 'cmp:compras_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Compras</div> 
        {% else %}
        <table class= "table table-striped table-hover dt-responsive nowrap" style="width:100%">
            <thead>
                <th>Id</th>
                <th>Fecha</th>
                <th>Observación</th>
                <th>Nro. Factura</th>
                <th>F. factura</th>
                <th>Sub Total</th>                
                <th>Descuento</th>
                <th>Total</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id}}</td>
                    <td>{{ item.fecha_compra }}</td>
                    <td>{{ item.observacion }}</td>
                    <td>{{ item.no_factura}}</td>
                    <td>{{ item.fecha_factrua }}</td>
                    <td>{{ item.subtotal }}</td>
                    <td>{{ item.descuento }}</td>
                    <td>{{ item.total }}</td>
                    <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>

                    <td>
                        <a class="btn btn-warning btn-circle" href="#"><i class="far fa-edit"></i></a>                          
                          
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
        {% endif %}
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script>
    //Call the dataTables jQuery plugin
    $(document).ready(function(){
      $('.table').DataTable({
        "languaje": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ resgistros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ resgistros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(Filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate":{
            "sFirst": "<span class= 'fa fa-angle-double-left'></span>",
            "sLast": "<span class= 'fa fa-angle-double-right></span>",
            "sNext": "<span class= 'fa fa-angle-right'></span>",
            "sPrevious": "<span class= 'fa fa-angle-left'></span>",
          },
          "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
</script>

{% endblock %}

cmp/templates/cmp/inactivar_prv.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">

        <form method="POST" class="form inline">
            <!-- Pending Requests Card Example -->
            {% csrf_token %}
            <div class="col">
                <div class="card border-left-danger shadow h-100 py-1">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase">
                                    <div class="alert">
                                        ¿ Inactivar <b>{{obj.descripcion}}</b>?
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="button" class="btn btn-danger" id="btnInactivar"><i class="fas fa-question-circle"></i>Si,
                                    Inactivar</button>
                                <button type='button' class="btn btn-success" onclick="return cerrar_modal()">
                                    No, Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
$(document).ready(function(){

    var token = $('input[name=csrfmiddlewaretoken]').val();
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", token);
            }
        }
     })


    $("#btnInactivar").click(function(e){
       e.preventDefault();
       // alert("Probando");
       var id = {{ obj.id }}; 
       var template="{% url 'cmp:proveedor_inactivar' obj.id %}";
       //template += id;
       var data = {"id":id};
       data = JSON.stringify(data);

       $.ajax({
         type: "POST",
         url: template,
         data: data,
         beforeSend: function(xhr, settings){
            $.ajaxSettings.beforeSend(xhr, settings);
         },
         success: function(response){
             console.log(response);
             cerrar_modal();
             //alert(response);
             var tipo=(response.startsWith('Proveedor no existe') ? 'red':'green' );
             mensaje(response, tipo);
         },
         error: function(jqXHR, textStatus, errorThrow){
             console.log(textStatus, errorThrow);
             mensaje(errorThrow, 'red');
             cerrar_modal();
         }
       });
    });

});

</script>

cmp/templates/cmp/proveedor_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_edit' obj.pk %}">
            {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_new' %}">
            {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                    {% else %}
                    <div class="card border-left-success shadow h-100 py-2">
                        {% endif %}
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        {% if obj %} Editar {% else %} Nuevo {% endif %} Proveedor
                                    </div>
                                    <div class="dropdown-divider"></div>
                                    {% csrf_token %}
                                    <div class="row">
                                        {{ form.as_p }}
                                    </div>
                                    <div class="dropdown-divider"></div>
                                    <div class="row">
                                        <div class="col">
                                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>                                            
                                            <buttob type='button' class="btn btn-success" onclick="return cerrar_modal()">Cancelar</buttob>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-auto">
                                    <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </form>

    </div>
</div>

cmp/templates/cmp/proveedor_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedores</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" onclick="return abrir_modal('{% url 'cmp:proveedor_new' %}')"><i class="far fa-calendar-plus"></i>  Nuevo</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Proveedores</div> 
        {% else %}
        <table class= "table table-striped table-hover dt-responsive nowrap" style="width:100%">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Dirección</th>
                <th>Contacto</th>
                <th>Teléfono</th>
                <th>EMail</th>                
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id}}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.direccion }}</td>
                    <td>{{ item.contacto}}</td>
                    <td>{{ item.telefono }}</td>
                    <td>{{ item.email }}</td>
                    <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>

                    <td>
                        <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')">                           
                          <i class="far fa-edit"></i> </button>
                        <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_inactivar' item.id %}')">                           
                          <i class="far fa-times-circle"></i> </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
        {% endif %}
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script>
    //Call the dataTables jQuery plugin
    $(document).ready(function(){
      $('.table').DataTable({
        "languaje": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ resgistros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ resgistros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(Filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate":{
            "sFirst": "<span class= 'fa fa-angle-double-left'></span>",
            "sLast": "<span class= 'fa fa-angle-double-right></span>",
            "sNext": "<span class= 'fa fa-angle-right'></span>",
            "sPrevious": "<span class= 'fa fa-angle-left'></span>",
          },
          "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
</script>

{% endblock %}